### ISSUE TITLE
Minor bug in XElement.add(child)

### ISSUE THREAD

**Issue by PureFox48** [Deijin27/wren-xsequence#1]
Firstly, thanks for writing this which should be a useful addition to the Wren armory :)

When trying to add a list of children to an XElement, I noticed that there was a bug in line 706 of xsequence.wren where:
```javascript
for (i in Sequence)
```
should, of course, be:
```javascript
for (i in child)
```
Perhaps you could fix this when you have time.

**Comment by Deijin27** [comment]
Thanks. I had fun writing it.
I'll get that fixed soon.
