### ISSUE TITLE
Parsing problems

### ISSUE THREAD

**Issue by PureFox48** [Deijin27/wren-xsequence#2]
I've turned my attention now to XML parsing and was trying to parse the following fragment, with a view to extracting the 'name' attributes from all 'Student' elements, when I ran into some problems.
```javascript
import "./xsequence" for XDocument

var xml = """
<Students>
  <Student Name="April" Gender="F" DateOfBirth="1989-01-02" />
  <Student Name="Bob" Gender="M"  DateOfBirth="1990-03-04" />
  <Student Name="Chad" Gender="M"  DateOfBirth="1991-05-06" />
  <Student Name="Dave" Gender="M"  DateOfBirth="1992-07-08">
    <Pet Type="dog" Name="Rover" />
  </Student>
  <Student DateOfBirth="1993-09-10" Gender="F" Name="&#x00C9;mily" />
</Students>
"""
var doc = XDocument.parse(xml)
var names = doc.root.elements("Student").map { |el| el.attribute("Name").value }.toList
System.print(names)
```
 I traced these problems back to the following lines in xsequence.wren: 

line 738: ```return parser.parserDocument(text)``` - this method shouldn't take any parameters.
(similar problem at lines 548 and 582)
line 540:```unexpected(c, "Invalid escape sequence")```- this method should take one rather than two parameters.
(similar problem at line 536)

If I alter those method calls to to take the correct number of arguments and also get rid of the acute accent so the last name is simply "Emily" rather than "Émily" then it works fine and I get the expected output:

```
[April, Bob, Chad, Dave, Emily]
```

So the first two problems should be easy to fix.

On the last problem, I think it would be worthwhile supporting Unicode character references (perhaps in a future version) as accented characters crop up quite a lot in my experience.

**Comment by Deijin27** [comment]
Fixed the issues and I've implemented the unicode escape support.

Took me a bit to figure out that Num.fromString could handle hex by adding "0x" to the start. We need to make that more clear in the documentation, currently it says something that feels misleading:

> Num.fromString(value)
>
> Attempts to parse value as a decimal literal and return it as an instance of Num. If the number cannot be parsed null will be returned.
>
> It is a runtime error if value is not a string.

**Comment by PureFox48** [comment]
Excellent, thanks :)

I agree that the docs for ```Num.fromString(value)``` could be clearer though it might be best to leave that for now as I think there's a very good chance that ```0o``` and ``0b`` will be added for octal and binary literals in v0.5.0  and the method / docs will therefore need updating to cope with those as well.
